### PR TITLE
Load MathJax over HTTPS

### LINKED ISSUE #12: MathJax is not loaded in an HTTPS environment
I was looking at the Git Intro lesson and noticed in the web console that there were issues loading and referencing MathJax. It turns out that it is loaded from an HTTP URL and is blocked (in Firefox at least) because of that.

The line causing the issue appears to be
https://github.com/coderefinery/jekyll-common/blob/5b5382f2d7d65bf4fe9579c0cb9c16192e78f85a/includes/js.html#L15

I can open a pull request shortly to update this, though the Git Intro lessons then needs an update of this submodule I think. (I am still a bit scared of submodules. ;))

### PR DESCRIPTION
**Pull request by bencomp**
I am pretty sure this fixes #12.

### CODE REVIEW

**Comment by rkdarst** [comment]
This makes sense to me - thanks for the contribution!

Hm, there is no license in this repository, which we should probably clarify before we accept contributions.  Can we discuss Monday and get back to you?

**Comment by bast** [comment]
Thanks @bencomp! Sorry for the missing license. I am working on it in #14.

**Comment by bast** [comment]
Now we can merge if @bencomp agrees to current license terms? (MIT license)

**Comment by bencomp** [comment]
This change to me seems so trivial I doubt I can claim any copyright to it, but yes, I agree to have it released under the MIT license.

**Comment by bast** [comment]
:-) Thanks again!

**Comment by bast** [comment]
Now we need to propagate this change to the lessons. I will do that very soon.

**Pull request merged**
