### PR TITLE
clarify license; closes #14

### LINKED ISSUE #14: There is no license here
This license doesn't have a license, and I don't know the history of it.

### PR DESCRIPTION
**Pull request by bast**
@rkdarst @annefou @schildwaechter as contributors to this repo, do you agree to this license clarification to license the code under MIT with a clarification about the origin of some of the sources?

### CODE REVIEW

**Comment by rkdarst** [comment]
Yes, I agree.

>

**Comment by bast** [comment]
@annefou ok also for you?

**Comment by annefou** [comment]
Yes! Sorry I missed that one!

**Comment by schildwaechter** [comment]
I agree

**Comment by bast** [comment]
Just for info: we will probably switch to Sphinx for lesson material and then probably handle common look using themes so this will become easier in future.

**Pull request merged**
